import { useState, useEffect } from "react";

const currencySymbols = {
  USD: "$",
  EUR: "€",
  JPY: "¥",
  GBP: "£",
  AUD: "A$",
  CAD: "C$",
  CHF: "CHF",
  CNY: "¥",
  SEK: "kr",
  NZD: "NZ$",
  MXN: "$",
  SGD: "S$",
  HKD: "HK$",
  NOK: "kr",
  KRW: "₩",
  TRY: "₺",
  RUB: "₽",
  INR: "₹",
  BRL: "R$",
  ZAR: "R",
  PLN: "zł",
  PHP: "₱",
  CZK: "Kč",
  IDR: "Rp",
  HUF: "Ft",
  MYR: "RM",
  THB: "฿",
  ILS: "₪",
  CLP: "$",
  PKR: "₨",
  BDT: "৳",
  VND: "₫",
  NGN: "₦",
  KZT: "₸",
  AED: "د.إ",
  SAR: "﷼",
  EGP: "£",
  DZD: "د.ج",
  MAD: "د.م.",
  UAH: "₴",
  KES: "KSh",
  ARS: "$",
  COP: "$",
  PEN: "S/.",
  LKR: "Rs",
  RON: "lei",
  BGN: "лв",
  HRK: "kn",
  BHD: ".د.ب",
  OMR: "﷼",
  QAR: "﷼",
  KWD: "د.ك",
  JOD: "د.ا",
  LBP: "ل.ل",
  BAM: "KM",
  MKD: "ден",
  GEL: "₾",
  TND: "د.ت",
  XAF: "FCFA",
  XOF: "CFA",
  MUR: "₨",
  MGA: "Ar",
  TZS: "TSh",
  UGX: "USh",
  GHS: "₵",
  RSD: "дин",
  ISK: "kr",
  MOP: "MOP$",
  NPR: "₨",
  NAD: "$",
  BWP: "P",
  ZMW: "ZK",
  BYN: "Br",
  AZN: "₼",
  IQD: "ع.د",
  AFN: "؋",
  KGS: "с",
  UZS: "сўм",
  MMK: "K",
  MNT: "₮",
  LAK: "₭",
  KPW: "₩",
  IRR: "﷼",
  SYP: "£",
  ETB: "Br",
  DJF: "Fdj",
  SOS: "Sh",
  GNF: "FG",
  CDF: "FC",
  AOA: "Kz",
  SDG: "ج.س.",
  BZD: "BZ$",
  HTG: "G",
  JMD: "J$",
  TTD: "TT$",
  BBD: "$",
  XCD: "$",
  ANG: "ƒ",
  AWG: "ƒ",
  SRD: "$",
  SZL: "E",
  LSL: "L",
  MWK: "MK",
  SLL: "Le",
  ZWL: "$",
  BIF: "FBu",
  RWF: "FRw",
  SCR: "₨",
  MVR: "Rf",
  MZN: "MT",
  PGK: "K",
  SBD: "$",
  TOP: "T$",
  VUV: "Vt",
  FJD: "$",
  WST: "T",
  KID: "$",
  TVD: "$",
};

const useCurrencySymbol = (currencyCode) => {
  const [symbol, setSymbol] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    if (currencyCode && currencySymbols[currencyCode]) {
      setSymbol(currencySymbols[currencyCode]);
      setError("");
    } else {
      setSymbol("");
      setError("No Symbol with that code");
    }
  }, [currencyCode]);

  return symbol;
};

export default useCurrencySymbol;
